AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: true

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20
