plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Metrics/BlockLength:
  Max: 40

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 20

Layout/LineLength:
  Max: 200

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false